##' For more information see: \itemize{ \item{For
##' BEAST1}{\url{http://www.phylo.org/rest/beast2_xsede.html} and the
##' BEAST2 website \url{http://beast2.org}} \item{For
##' BEAST2}{\url{http://www.phylo.org/index.php/rest/beast_tg.html}
##' and the BEAST website \url{http://beast.bio.ed.ac.uk}} }
##'
##' Specifying the number of partitions and patterns in the alignments
##' are not required by BEAST, but are used by CIPRES to optimize the
##' computing parameters for improved run times.
##'
##' @title Submit a BEAST or BEAST2 analysis
##' @param input_file An XML input file generated by BEAUTI2
##' @param beast_version Which version of BEAST2 should be used?
##' @template max_runtime
##' @param use_beagle Should the BEAGLE library be used?
##' @param n_patterns How many patterns are in the alignment used in
##'     the analysis?
##' @param n_partitions How many partitions are in the analysis?
##' @param use_seed If \code{NULL} (default), a random seed will be
##'     generated by BEAST, otherwise specify your own seed.
##' @param overwrite_logs Should existing log files on the server be
##'     overwritten?
##' @template get_email
##' @template job_name
##' @template dotdotdot
##' @importFrom assertthat assert_that is.count is.flag
##' @importFrom httr upload_file
##' @rdname beast
##' @export
cipres_submit_beast2 <- function(input_file,
                                 beast_version = c("2.3.0", "2.1.3"),
                                 max_runtime = 10,
                                 use_beagle = TRUE,
                                 n_patterns,
                                 n_partitions = 0,
                                 use_seed = NULL,
                                 overwrite_logs = TRUE,
                                 job_name = NULL,
                                 get_email = TRUE, ...) {


    ## documentation: http://www.phylo.org/rest/beast2_xsede.html

    beast_version <- match.arg(beast_version)
    beast_version <- switch(beast_version,
                            "2.3.0" = "30",
                            "2.1.3" = "13")

    assertthat::assert_that(assertthat::is.count(max_runtime))
    assertthat::assert_that(assertthat::is.count(n_patterns))
    assertthat::assert_that(assertthat::is.count(n_partitions))
    assertthat::assert_that(assertthat::is.flag(use_beagle))
    assertthat::assert_that(assertthat::is.flag(overwrite_logs))

    input_file <- normalizePath(input_file)
    check_file(input_file)

    bdy <- list(
        `input.infile_` = httr::upload_file(input_file),
        `vparam.runtime_` = max_runtime,
        `vparam.nu_patterns_` = n_patterns,
        `vparam.which_beast2_` = beast_version,
        `vparam.no_beagle_` = as.numeric(!use_beagle),
        `vparam.overwrite_logs_` = as.numeric(overwrite_logs)
        )

    bdy <- beast_check_partitions(bdy, n_partitions)
    bdy <- beast_use_seed(bdy, use_seed)
    bdy <- add_meta_data(bdy, get_email, job_name)

    bdy <- lapply(bdy, as.character)
    bdy$"tool" <- "BEAST2_XSEDE"

    res <- cipres_POST(body = bdy, ...)
    cipres_process_results(res)
}
