##' Find and download the files associated with a job.
##'
##' Be careful, files with identical names will be silently overwritten.
##'
##' By only providing a job handle to \code{cipres_download}, all the
##' files generated by the job will be downloaded. To download only
##' one or a subset of these files, you can use regular expression
##' pattern matching.
##'
##' @title List and download files associated with a job
##' @param job_handle the job identified
##' @return \code{cipres_list_files} returns a data frame listing all
##'     the files associated with a job. \code{cipres_download_file}
##'     and \code{cipres_download_all} returns whether the files were
##'     successfully downloaded.
##' @export
##' @importFrom assertthat assert_that is.string
##' @importFrom xml2 xml_text xml_find_all
##' @examples
##' \dontrun{
##' ### List the files associated with the oldest job
##' ### cipres_list_files(cipres_list_jobs$handle[1])
##'
##' ### Download all the files associated with the oldest job
##' ### cipres_download(cipres_list_jobs$handle[1], tempdir())
##' }
cipres_list_files <- function(job_handle, ...) {

    assertthat::assert_that(assertthat::is.string(job_handle))

    res <- cipres_GET(path = paste(job_handle, "output", sep = "/"),
                      ...)

    what <- c("outputDocumentId", "filename", "length")
    res_lst <- lapply(what, function(x) {
        xml2::xml_text(
            xml2::xml_find_all(res, paste0(".//", x)))
    })

    res <- data.frame(res_lst, stringsAsFactors = FALSE)
    names(res) <- what
    res
}

cipres_download_file <- function(job_handle, file_id, file_name,
                                 outfile, show_progress, ...) {

    assertthat::assert_that(assertthat::is.string(job_handle))
    assertthat::assert_that(assertthat::is.string(file_id))
    assertthat::assert_that(assertthat::is.string(file_name))
    assertthat::assert_that(assertthat::is.string(outfile))
    assertthat::assert_that(assertthat::is.flag(show_progress))

    if (show_progress)
        message("Downloading ", sQuote(file_name), "... ", appendLF = FALSE)

    res <- cipres_GET(path = paste(job_handle, "output", file_id, sep = "/"),
                      ...)

    if (show_progress)
        message("DONE.")

    cat(res, file = outfile)
    invisible(file.exists(outfile))
}

##' @param outdir the path where the files should be downloaded
##' @param pattern an optional regular expression to download only the
##'     files that match the pattern
##' @param ignore.case should pattern matching be case sensitive?
##' @param show_progress should the progress of the files being
##'     downloaded be displayed?
##' @template dotdotdot
##' @export
##' @rdname cipres_list_files
##' @importFrom assertthat assert_that is.dir
cipres_download <- function(job_handle, outdir, pattern = NULL,
                            ignore.case = FALSE, show_progress = TRUE,
                            ...) {

    assertthat::assert_that(assertthat::is.dir(outdir))

    lst_files <- cipres_list_files(job_handle = job_handle, ...)

    if (!is.null(pattern)) {
        which_files <- grep(pattern = pattern,
                            x = lst_files[["filename"]],
                            ignore.case = ignore.case)
        lst_files <- lst_files[which_files, ]
    }
    res <- apply(lst_files, 1, function(x) {
        cipres_download_file(job_handle = job_handle,
                             file_id = x["outputDocumentId"],
                             file_name = x["filename"],
                             outfile = file.path(outdir, x["filename"]),
                             show_progress = show_progress,
                             ...)
    })
    names(res) <- lst_files[["filename"]]
    invisible(res)
}
